"""

Copyright (c) 2020 Taoidle
CV Tool is licensed under Mulan PSL v2.
You can use this software according to the terms and conditions of the Mulan PSL v2.
You may obtain a copy of Mulan PSL v2 at:
         http://license.coscl.org.cn/MulanPSL2
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
See the Mulan PSL v2 for more details.

"""
from PyQt5.QtWidgets import QToolBox, QWidget, QVBoxLayout, QGroupBox, QToolButton


class ToolBox(QWidget):

    def init_default_box(self):
        # 初始化工具盒
        tool_box = QToolBox()

        group_box_1 = QGroupBox()
        group_box_1.setMaximumWidth(280)
        v_box_1 = QVBoxLayout()
        group_box_2 = QGroupBox()
        group_box_2.setMaximumWidth(280)
        v_box_2 = QVBoxLayout()
        group_box_3 = QGroupBox()
        group_box_3.setMaximumWidth(280)
        v_box_3 = QVBoxLayout()
        group_box_4 = QGroupBox()
        group_box_4.setMaximumWidth(280)
        v_box_4 = QVBoxLayout()
        group_box_5 = QGroupBox()
        group_box_5.setMaximumWidth(280)
        v_box_5 = QVBoxLayout()
        group_box_6 = QGroupBox()
        group_box_6.setMaximumWidth(280)
        v_box_6 = QVBoxLayout()
        group_box_7 = QGroupBox()
        group_box_7.setMaximumWidth(280)
        v_box_7 = QVBoxLayout()
        group_box_8 = QGroupBox()
        group_box_8.setMaximumWidth(280)
        v_box_8 = QVBoxLayout()
        group_box_9 = QGroupBox()
        group_box_9.setMaximumWidth(280)
        v_box_9 = QVBoxLayout()

        self.box_1_button_1 = QToolButton()
        self.box_1_button_1.setText('恢复原图')
        self.box_1_button_1.setAutoRaise(True)
        self.box_1_button_1.setFixedSize(220, 30)
        self.box_1_button_2 = QToolButton()
        self.box_1_button_2.setText('上一步图像')
        self.box_1_button_2.setAutoRaise(True)
        self.box_1_button_2.setFixedSize(220, 30)
        self.box_1_button_3 = QToolButton()
        self.box_1_button_3.setText('灰度化')
        self.box_1_button_3.setAutoRaise(True)
        self.box_1_button_3.setFixedSize(220, 30)
        self.box_1_button_4 = QToolButton()
        self.box_1_button_4.setText('反相')
        self.box_1_button_4.setAutoRaise(True)
        self.box_1_button_4.setFixedSize(220, 30)
        self.box_1_button_5 = QToolButton()
        self.box_1_button_5.setText('二值化')
        self.box_1_button_5.setAutoRaise(True)
        self.box_1_button_5.setFixedSize(220, 30)
        self.box_1_button_6 = QToolButton()
        self.box_1_button_6.setText('自动二值化')
        self.box_1_button_6.setAutoRaise(True)
        self.box_1_button_6.setFixedSize(220, 30)
        self.box_1_button_7 = QToolButton()
        self.box_1_button_7.setText('亮度对比度')
        self.box_1_button_7.setAutoRaise(True)
        self.box_1_button_7.setFixedSize(220, 30)
        self.box_1_button_8 = QToolButton()
        self.box_1_button_8.setText('图像叠加')
        self.box_1_button_8.setAutoRaise(True)
        self.box_1_button_8.setFixedSize(220, 30)
        self.box_1_button_9 = QToolButton()
        self.box_1_button_9.setText('分量提取')
        self.box_1_button_9.setAutoRaise(True)
        self.box_1_button_9.setFixedSize(220, 30)

        self.box_2_button_1 = QToolButton()
        self.box_2_button_1.setText('水平镜像')
        self.box_2_button_1.setAutoRaise(True)
        self.box_2_button_1.setFixedSize(220, 30)
        self.box_2_button_2 = QToolButton()
        self.box_2_button_2.setText('垂直镜像')
        self.box_2_button_2.setAutoRaise(True)
        self.box_2_button_2.setFixedSize(220, 30)
        self.box_2_button_3 = QToolButton()
        self.box_2_button_3.setText('逆时针 90°')
        self.box_2_button_3.setAutoRaise(True)
        self.box_2_button_3.setFixedSize(220, 30)
        self.box_2_button_4 = QToolButton()
        self.box_2_button_4.setText('顺时针 90°')
        self.box_2_button_4.setAutoRaise(True)
        self.box_2_button_4.setFixedSize(220, 30)
        self.box_2_button_5 = QToolButton()
        self.box_2_button_5.setText('逆时针旋转')
        self.box_2_button_5.setAutoRaise(True)
        self.box_2_button_5.setFixedSize(220, 30)
        self.box_2_button_6 = QToolButton()
        self.box_2_button_6.setText('顺时针旋转')
        self.box_2_button_6.setAutoRaise(True)
        self.box_2_button_6.setFixedSize(220, 30)

        self.box_3_button_1 = QToolButton()
        self.box_3_button_1.setText('椒盐噪声')
        self.box_3_button_1.setAutoRaise(True)
        self.box_3_button_1.setFixedSize(220, 30)
        self.box_3_button_2 = QToolButton()
        self.box_3_button_2.setText('高斯噪声')
        self.box_3_button_2.setAutoRaise(True)
        self.box_3_button_2.setFixedSize(220, 30)

        self.box_4_button_1 = QToolButton()
        self.box_4_button_1.setText('均值滤波')
        self.box_4_button_1.setAutoRaise(True)
        self.box_4_button_1.setFixedSize(220, 30)
        self.box_4_button_2 = QToolButton()
        self.box_4_button_2.setText('中值滤波')
        self.box_4_button_2.setAutoRaise(True)
        self.box_4_button_2.setFixedSize(220, 30)
        self.box_4_button_3 = QToolButton()
        self.box_4_button_3.setText('方框滤波')
        self.box_4_button_3.setAutoRaise(True)
        self.box_4_button_3.setFixedSize(220, 30)
        self.box_4_button_4 = QToolButton()
        self.box_4_button_4.setText('高斯滤波')
        self.box_4_button_4.setAutoRaise(True)
        self.box_4_button_4.setFixedSize(220, 30)
        self.box_4_button_5 = QToolButton()
        self.box_4_button_5.setText('双边滤波')
        self.box_4_button_5.setAutoRaise(True)
        self.box_4_button_5.setFixedSize(220, 30)

        self.box_5_button_1 = QToolButton()
        self.box_5_button_1.setText("Canny算子")
        self.box_5_button_1.setAutoRaise(True)
        self.box_5_button_1.setFixedSize(220, 30)
        self.box_5_button_2 = QToolButton()
        self.box_5_button_2.setText("Sobel算子")
        self.box_5_button_2.setAutoRaise(True)
        self.box_5_button_2.setFixedSize(220, 30)
        self.box_5_button_3 = QToolButton()
        self.box_5_button_3.setText("Laplacian算子")
        self.box_5_button_3.setAutoRaise(True)
        self.box_5_button_3.setFixedSize(220, 30)
        self.box_5_button_4 = QToolButton()
        self.box_5_button_4.setText("Scharr滤波器")
        self.box_5_button_4.setAutoRaise(True)
        self.box_5_button_4.setFixedSize(220, 30)
        self.box_5_button_5 = QToolButton()
        self.box_5_button_5.setText('标准霍夫变换')
        self.box_5_button_5.setAutoRaise(True)
        self.box_5_button_5.setFixedSize(220, 30)
        self.box_5_button_6 = QToolButton()
        self.box_5_button_6.setText('累计概率霍夫变换')
        self.box_5_button_6.setAutoRaise(True)
        self.box_5_button_6.setFixedSize(220, 30)
        self.box_5_button_7 = QToolButton()
        self.box_5_button_7.setText('霍夫圆变换')
        self.box_5_button_7.setAutoRaise(True)
        self.box_5_button_7.setFixedSize(220, 30)
        self.box_5_button_8 = QToolButton()
        self.box_5_button_8.setText('DCT变换')
        self.box_5_button_8.setAutoRaise(True)
        self.box_5_button_8.setFixedSize(220, 30)

        self.box_6_button_1 = QToolButton()
        self.box_6_button_1.setText("膨胀")
        self.box_6_button_1.setAutoRaise(True)
        self.box_6_button_1.setFixedSize(220, 30)
        self.box_6_button_2 = QToolButton()
        self.box_6_button_2.setText("腐蚀")
        self.box_6_button_2.setAutoRaise(True)
        self.box_6_button_2.setFixedSize(220, 30)
        self.box_6_button_3 = QToolButton()
        self.box_6_button_3.setText("开运算")
        self.box_6_button_3.setAutoRaise(True)
        self.box_6_button_3.setFixedSize(220, 30)
        self.box_6_button_4 = QToolButton()
        self.box_6_button_4.setText("闭运算")
        self.box_6_button_4.setAutoRaise(True)
        self.box_6_button_4.setFixedSize(220, 30)
        self.box_6_button_5 = QToolButton()
        self.box_6_button_5.setText("顶帽")
        self.box_6_button_5.setAutoRaise(True)
        self.box_6_button_5.setFixedSize(220, 30)
        self.box_6_button_6 = QToolButton()
        self.box_6_button_6.setText("黑帽")
        self.box_6_button_6.setAutoRaise(True)
        self.box_6_button_6.setFixedSize(220, 30)
        self.box_6_button_7 = QToolButton()
        self.box_6_button_7.setText("形态学梯度")
        self.box_6_button_7.setAutoRaise(True)
        self.box_6_button_7.setFixedSize(220, 30)

        self.box_7_button_1 = QToolButton()
        self.box_7_button_1.setText("向上采样 ")
        self.box_7_button_1.setAutoRaise(True)
        self.box_7_button_1.setFixedSize(220, 30)
        self.box_7_button_2 = QToolButton()
        self.box_7_button_2.setText("向下采样")
        self.box_7_button_2.setAutoRaise(True)
        self.box_7_button_2.setFixedSize(220, 30)
        self.box_7_button_3 = QToolButton()
        self.box_7_button_3.setText('拉普拉斯金字塔')
        self.box_7_button_3.setAutoRaise(True)
        self.box_7_button_3.setFixedSize(220, 30)

        v_box_1.addWidget(self.box_1_button_1)
        v_box_1.addWidget(self.box_1_button_2)
        v_box_1.addWidget(self.box_1_button_3)
        v_box_1.addWidget(self.box_1_button_4)
        v_box_1.addWidget(self.box_1_button_5)
        v_box_1.addWidget(self.box_1_button_6)
        v_box_1.addWidget(self.box_1_button_7)
        v_box_1.addWidget(self.box_1_button_8)
        v_box_1.addWidget(self.box_1_button_9)
        v_box_1.addStretch(0)
        group_box_1.setLayout(v_box_1)

        v_box_2.addWidget(self.box_2_button_1)
        v_box_2.addWidget(self.box_2_button_2)
        v_box_2.addWidget(self.box_2_button_3)
        v_box_2.addWidget(self.box_2_button_4)
        v_box_2.addWidget(self.box_2_button_5)
        v_box_2.addWidget(self.box_2_button_6)
        v_box_2.addStretch(0)
        group_box_2.setLayout(v_box_2)

        v_box_3.addWidget(self.box_3_button_1)
        v_box_3.addWidget(self.box_3_button_2)
        v_box_3.addStretch(0)
        group_box_3.setLayout(v_box_3)

        v_box_4.addWidget(self.box_4_button_1)
        v_box_4.addWidget(self.box_4_button_2)
        v_box_4.addWidget(self.box_4_button_3)
        v_box_4.addWidget(self.box_4_button_4)
        v_box_4.addWidget(self.box_4_button_5)
        v_box_4.addStretch(0)
        group_box_4.setLayout(v_box_4)

        v_box_5.addWidget(self.box_5_button_1)
        v_box_5.addWidget(self.box_5_button_2)
        v_box_5.addWidget(self.box_5_button_3)
        v_box_5.addWidget(self.box_5_button_4)
        v_box_5.addWidget(self.box_5_button_5)
        v_box_5.addWidget(self.box_5_button_6)
        v_box_5.addWidget(self.box_5_button_7)
        v_box_5.addWidget(self.box_5_button_8)
        v_box_5.addStretch(0)
        group_box_5.setLayout(v_box_5)

        v_box_6.addWidget(self.box_6_button_1)
        v_box_6.addWidget(self.box_6_button_2)
        v_box_6.addWidget(self.box_6_button_3)
        v_box_6.addWidget(self.box_6_button_4)
        v_box_6.addWidget(self.box_6_button_5)
        v_box_6.addWidget(self.box_6_button_6)
        v_box_6.addWidget(self.box_6_button_7)
        v_box_6.addStretch(0)
        group_box_6.setLayout(v_box_6)

        v_box_7.addWidget(self.box_7_button_1)
        v_box_7.addWidget(self.box_7_button_2)
        v_box_7.addWidget(self.box_7_button_3)
        v_box_7.addStretch(0)
        group_box_7.setLayout(v_box_7)

        tool_box.addItem(group_box_1, "图像基本处理")
        tool_box.addItem(group_box_2, "图像位置变换")
        tool_box.addItem(group_box_3, "图像噪声添加")
        tool_box.addItem(group_box_4, "图像滤波处理")
        tool_box.addItem(group_box_5, "图像变换")
        tool_box.addItem(group_box_6, "图像形态学操作")
        tool_box.addItem(group_box_7, "图像金字塔")

        vbox = QVBoxLayout()
        vbox.addWidget(tool_box)
        self.setLayout(vbox)
